### ISSUE TITLE
Calling 'depends_on :postgresql' is deprecated

### ISSUE THREAD

**Issue by ellisvalentiner** [timescale/homebrew-tap#2]
```sh
$ brew install timescaledb
Warning: Calling 'depends_on :postgresql' is deprecated!
Use 'depends_on "postgresql"' instead.
/usr/local/Homebrew/Library/Taps/timescale/homebrew-tap/timescaledb.rb:9:in `<class:Timescaledb>'
Please report this to the timescale/tap tap!

==> Installing timescaledb from timescale/tap
Error: no implicit conversion of Symbol into String
Please report this bug:
  https://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/formulary.rb:363:in `extname'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:363:in `loader_for'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:280:in `factory'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:33:in `to_formula'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:96:in `block in expand'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/delegate.rb:341:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/delegate.rb:341:in `block in delegating_block'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:83:in `expand'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1478:in `recursive_dependencies'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:194:in `expand'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1484:in `recursive_requirements'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:420:in `runtime_requirements'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:432:in `expand_requirements'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:376:in `compute_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:133:in `verify_deps_exist'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:126:in `prelude'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:336:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:227:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:225:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:225:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

**Comment by RobAtticus** [comment]
Thanks to @silsha for providing a fix. Please try again and let me know if there are still problems.
